# Tarefa 03

- Leia os enunciados com atenção
- Saiba que pode haver mais de uma resposta correta
- Insira novas células de código sempre que achar necessário
- Em caso de dúvidas, procure os Tutores
- Divirta-se :)

In [1]:
import pandas as pd
import requests

####  1) Lendo de APIs
Vimos em aula como carregar dados públicos do governo através de um API (*Application Programming Interface*). No exemplo de aula, baixamos os dados de pedidos de verificação de limites (PVL) realizados por estados, e selecionamos apenas aqueles referentes ao estado de São Paulo.

1. Repita os mesmos passos feitos em aula, mas selecione os PVLs realizados por municípios no estado do Rio de Janeiro.
2. Quais são os três *status* das solicitações mais frequentes na base? Quais são suas frequências?
3. Construa uma nova variável que contenha o ano do **status**. Observe que ```data_status``` vem como tipo *object* no **DataFrame**. Dica: você pode usar o método ```.str``` para transformar o tipo da variável em string, em seguida um método como [**slice()**](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.slice.html) ou [**split()**](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.split.html).
4. Indique a frequência de cada ano do campo construído no item (3).

In [12]:
# 1) Seu código aqui
url = "https://apidatalake.tesouro.gov.br/ords/sadipem/tt/pvl"

r = requests.get(url)
r.status_code

200

In [13]:
data_json = r.json()

print(data_json['items'])

[{'id_pleito': 55150, 'tipo_interessado': 'Município', 'interessado': 'Américo de Campos', 'cod_ibge': 3501806, 'uf': 'SP', 'num_pvl': 'PVL02.002702/2022-21', 'status': 'Deferido (PVL-IF)', 'num_processo': None, 'data_protocolo': None, 'tipo_operacao': 'Operação contratual interna', 'finalidade': 'Desenvolvimento sustentável', 'tipo_credor': 'Instituição Financeira Nacional', 'credor': 'Agência de Fomento do Estado de São Paulo', 'moeda': 'Real', 'valor': 3000000, 'pvl_assoc_divida': 0, 'pvl_contradado_credor': 1, 'data_status': '01/06/2022'}, {'id_pleito': 63659, 'tipo_interessado': 'Município', 'interessado': 'Carambeí', 'cod_ibge': 4104659, 'uf': 'PR', 'num_pvl': 'PVL02.008124/2022-37', 'status': 'Deferido', 'num_processo': '17944.100967/2023-38', 'data_protocolo': '2023-03-21T14:32:11Z', 'tipo_operacao': 'Operação contratual interna', 'finalidade': 'Infraestrutura', 'tipo_credor': 'Instituição Financeira Nacional', 'credor': 'Caixa Econômica Federal', 'moeda': 'Real', 'valor': 30000000, 'pvl_assoc_divida': 0, 'pvl_contradado_credor': 1, 'data_status': '24/03/2023'}, {'id_pleito': 70836, 'tipo_interessado': 'Município', 'interessado': 'Quiterianópolis', 'cod_ibge': 2311264, 'uf': 'CE', 'num_pvl': 'PVL02.000603/2025-58', 'status': 'Deferido (PVL-IF)', 'num_processo': None, 'data_protocolo': None, 'tipo_operacao': 'Operação contratual interna', 'finalidade': 'Infraestrutura', 'tipo_credor': 'Instituição Financeira Nacional', 'credor': 'Banco do Brasil S/A', 'moeda': 'Real', 'valor': 11175965, 'pvl_assoc_divida': 0, 'pvl_contradado_credor': 1, 'data_status': '24/04/2025'}, {'id_pleito': 72392, 'tipo_interessado': 'Município', 'interessado': 'Castro', 'cod_ibge': 4104907, 'uf': 'PR', 'num_pvl': 'PVL02.002077/2025-61', 'status': 'Deferido (PVL-IF)', 'num_processo': None, 'data_protocolo': None, 'tipo_operacao': 'Operação contratual interna', 'finalidade': 'Aquisição de terrenos, imóveis e/ou construção de instalações', 'tipo_credor': 'Instituição Financeira Nacional', 'credor': 'Agência de Fomento do Paraná S/A', 'moeda': 'Real', 'valor': 10000000, 'pvl_assoc_divida': 0, 'pvl_contradado_credor': 1, 'data_status': '25/11/2025'}, {'id_pleito': 72843, 'tipo_interessado': 'Município', 'interessado': 'Bebedouro', 'cod_ibge': 3506102, 'uf': 'SP', 'num_pvl': 'PVL02.000127/2026-56', 'status': 'Deferido (PVL-IF)', 'num_processo': None, 'data_protocolo': None, 'tipo_operacao': 'Operação contratual interna', 'finalidade': 'Infraestrutura', 'tipo_credor': 'Instituição Financeira Nacional', 'credor': 'Caixa Econômica Federal', 'moeda': 'Real', 'valor': 40000000, 'pvl_assoc_divida': 0, 'pvl_contradado_credor': 1, 'data_status': '13/02/2026'}, {'id_pleito': 70741, 'tipo_interessado': 'Município', 'interessado': 'Caruaru', 'cod_ibge': 2604106, 'uf': 'PE', 'num_pvl': 'PVL02.000350/2025-12', 'status': 'Deferido', 'num_processo': '17944.001201/2025-33', 'data_protocolo': '2025-03-20T14:33:58Z', 'tipo_operacao': 'Operação contratual interna', 'finalidade': 'Infraestrutura', 'tipo_credor': 'Instituição Financeira Nacional', 'credor': 'Caixa Econômica Federal', 'moeda': 'Real', 'valor': 75000000, 'pvl_assoc_divida': 0, 'pvl_contradado_credor': 1, 'data_status': '21/03/2025'}, {'id_pleito': 71267, 'tipo_interessado': 'Município', 'interessado': 'Manaus', 'cod_ibge': 1302603, 'uf': 'AM', 'num_pvl': 'PVL02.000829/2025-59', 'status': 'Encaminhado à PGFN com manifestação técnica favorável', 'num_processo': '17944.002513/2025-64', 'data_protocolo': '2025-06-23T12:17:32Z', 'tipo_operacao': 'Operação contratual interna (com garantia da União)', 'finalidade': 'Infraestrutura', 'tipo_credor': 'Instituição Financeira Nacional', 'credor': 'Banco do Brasil S/A', 'moeda': 'Real', 'valor': 500000000, 'pvl_assoc_divida': 0, 'pvl_contradado_credor': 1, 'data_status': '03/07/2025'}, {'id_pleito': 72462, 'tipo_interessado': 'Município', 'interessado': 'Balneário Rincão', 'cod_ibge': 4220000, 'uf': 'SC', 'num_pvl': 'PVL02.002099/2025-21', 'status': 'Deferido (PVL-IF)', 'num_processo': None, 'data_protocolo': None, 'tipo_operacao': 'Operação contratual interna', 'finalidade': 'Pró-Transporte', 'tipo_credor': 'Instituição Financeira Nacional', 'credor': 'Caixa Econômica Federal', 'moeda': 'Real', 'valor': 41380949.18, 'pvl_assoc_divida': 0, 'pvl_contradado_credor': 1, 'data_status': '26/11/2025'}, {'id_pleito': 72036, 'tipo_interessado': 'Município', 'interessado': 'Nova Crixás', 'cod_ibge': 5214838, 'uf': 'GO', 'num_pvl': 'PVL02.001519/2025-51', 'status': 'Assinado pelo interessado (retificação)', 'num_processo': '17944.004775/2025-63', 'data_protocolo': '2026-04-29T16:42:28Z', 'tipo_operacao': 'Operação contratual interna (com garantia da União)', 'finalidade': 'Infraestrutura', 'tipo_credor': 'Instituição Financeira Nacional', 'credor': 'Banco do Brasil S/A', 'moeda': 'Real', 'valor': 20000000, 'pvl_assoc_divida': 0, 'pvl_contradado_credor': 0, 'data_status': '13/05/2026'}, {'id_pleito': 73608, 'tipo_interessado': 'Município', 'interessado': 'Antônio João', 'cod_ibge': 5000906, 'uf': 'MS', 'num_pvl': 'PVL02.000485/2026-69', 'status': 'Em análise', 'num_processo': '17944.002231/2026-48', 'data_protocolo': '2026-05-07T15:12:43Z', 'tipo_operacao': 'Operação contratual interna (com garantia da União)', 'finalidade': 'Amortização de dívida', 'tipo_credor': 'Instituição Financeira Nacional', 'credor': 'Banco do Brasil S/A', 'moeda': 'Real', 'valor': 20000000, 'pvl_assoc_divida': 0, 'pvl_contradado_credor': 0, 'data_status': '14/05/2026'}, {'id_pleito': 73675, 'tipo_interessado': 'Município', 'interessado': 'Dores do Indaiá', 'cod_ibge': 3123205, 'uf': 'MG', 'num_pvl': 'PVL02.000842/2026-99', 'status': 'Em retificação pelo interessado (PVL-IF)', 'num_processo': None, 'data_protocolo': None, 'tipo_operacao': 'Operação contratual interna', 'finalidade': 'Infraestrutura', 'tipo_credor': 'Instituição Financeira Nacional', 'credor': 'Caixa Econômica Federal', 'moeda': 'Real', 'valor': 4000000, 'pvl_assoc_divida': 0, 'pvl_contradado_credor': 0, 'data_status': '12/05/2026'}, {'id_pleito': 53471, 'tipo_interessado': 'Município', 'interessado': 'Mauá da Serra', 'cod_ibge': 4115754, 'uf': 'PR', 'num_pvl': 'PVL02.001363/2022-66', 'status': 'Deferido (PVL-IF)', 'num_processo': None, 'data_protocolo': None, 'tipo_operacao': 'Operação contratual interna', 'finalidade': 'Aquisição de máquinas, equipamentos e veículos', 'tipo_credor': 'Instituição Financeira Nacional', 'credor': 'Agência de Fomento do Paraná S/A', 'moeda': 'Real', 'valor': 390000, 'pvl_assoc_divida': 0, 'pvl_contradado_credor': 1, 'data_status': '24/03/2022'}, {'id_pleito': 71443, 'tipo_interessado': 'Município', 'interessado': 'Santa Margarida', 'cod_ibge': 3157906, 'uf': 'MG', 'num_pvl': 'PVL02.001190/2025-29', 'status': 'Deferido (PVL-IF)', 'num_processo': None, 'data_protocolo': None, 'tipo_operacao': 'Operação contratual interna', 'finalidade': 'Aquisição de máquinas, equipamentos e veículos', 'tipo_credor': 'Instituição Financeira Nacional', 'credor': 'Banco de Desenvolvimento de Minas Gerais S/A', 'moeda': 'Real', 'valor': 2000000, 'pvl_assoc_divida': 0, 'pvl_contradado_credor': 1, 'data_status': '26/06/2025'}, {'id_pleito': 71450, 'tipo_interessado': 'Município', 'interessado': 'Mar Vermelho', 'cod_ibge': 2704906, 'uf': 'AL', 'num_pvl': 'PVL02.001197/2025-41', 'status': 'Deferido (PVL-IF)', 'num_processo': None, 'data_protocolo': None, 'tipo_operacao': 'Operação contratual interna', 'finalidade': 'Infraestrutura', 'tipo_credor': 'Instituição Financeira Nacional', 'credor': 'Caixa Econômica Federal', 'moeda': 'Real', 'valor': 6500000, 'pvl_assoc_divida': 0, 'pvl_contradado_credor': 1, 'data_status': '26/06/2025'}, {'id_pleito': 71523, 'tipo_interessado': 'Município', 'interessado': 'Ibirapuitã', 'cod_ibge': 4309951, 'uf': 'RS', 'num_pvl': 'PVL02.001249/2025-89', 'status': 'Deferido (PVL-IF)', 'num_processo': None, 'data_protocolo': None, 'tipo_operacao': 'Operação contratual interna', 'finalidade': 'Aquisição de terrenos, imóveis e/ou construção de instalações', 'tipo_credor': 'Instituição Financeira Nacional', 'credor': 'BADESUL Desenvolvimento S.A. - Agência de Fomento/RS', 'moeda': 'Real', 'valor': 5000000, 'pvl_assoc_divida': 0, 'pvl_contradado_credor': 1, 'data_status': '10/03/2026'}, {'id_pleito': 71905, 'tipo_interessado': 'Município', 'interessado': 'Tocos do Moji', 'cod_ibge': 3169059, 'uf': 'MG', 'num_pvl': 'PVL02.001608/2025-06', 'status': 'Deferido (PVL-IF)', 'num_processo': None, 'data_protocolo': None, 'tipo_operacao': 'Operação contratual interna', 'finalidade': 'Aquisição de máquinas, equipamentos e veículos', 'tipo_credor': 'Instituição Financeira Nacional', 'credor': 'Banco do Brasil S/A', 'moeda': 'Real', 'valor': 1000000, 'pvl_assoc_divida': 0, 'pvl_contradado_credor': 1, 'data_status': '22/12/2025'}, {'id_pleito': 54329, 'tipo_interessado': 'Município', 'interessado': 'Irecê', 'cod_ibge': 2914604, 'uf': 'BA', 'num_pvl': 'PVL02.001295/2022-35', 'status': 'Deferido', 'num_processo': '17944.100706/2022-37', 'data_protocolo': '2022-03-09T20:16:42Z', 'tipo_operacao': 'Operação contratual interna', 'finalidade': 'Infraestrutura', 'tipo_credor': 'Instituição Financeira Nacional', 'credor': 'Caixa Econômica Federal', 'moeda': 'Real', 'valor': 12000000, 'pvl_assoc_divida': 0, 'pvl_contradado_credor': 1, 'data_status': '10/03/2022'}, {'id_pleito': 67717, 'tipo_interessado': 'Município', 'interessado': 'Sobradinho', 'cod_ibge': 4320701, 'uf': 'RS', 'num_pvl': 'PVL02.000143/2024-87', 'status': 'Deferido (PVL-IF)', 'num_processo': None, 'data_protocolo': None, 'tipo_operacao': 'Operação contratual interna', 'finalidade': 'Aquisição de máquinas, equipamentos e veículos', 'tipo_credor': 'Instituição Financeira Nacional', 'credor': 'Banco do Estado do Rio Grande do Sul', 'moeda': 'Real', 'valor': 1400000, 'pvl_assoc_divida': 0, 'pvl_contradado_credor': 1, 'data_status': '25/01/2024'}, {'id_pleito': 68243, 'tipo_interessado': 'Município', 'interessado': 'São José dos Quatro Marcos', 'cod_ibge': 5107107, 'uf': 'MT', 'num_pvl': 'PVL02.000627/2024-26', 'status': 'Deferido (PVL-IF)', 'num_processo': None, 'data_protocolo': None, 'tipo_operacao': 'Operação contratual interna', 'finalidade': 'Infraestrutura', 'tipo_credor': 'Instituição Financeira Nacional', 'credor': 'Banco do Brasil S/A', 'moeda': 'Real', 'valor': 8893320, 'pvl_assoc_divida': 0, 'pvl_contradado_credor': 1, 'data_status': '17/05/2024'}, {'id_pleito': 64349, 'tipo_interessado': 'Município', 'interessado': 'Luziânia', 'cod_ibge': 5212501, 'uf': 'GO', 'num_pvl': 'PVL02.000042/2023-25', 'status': 'Arquivado por decurso de prazo', 'num_processo': '17944.101905/2023-43', 'data_protocolo': '2024-08-14T18:06:54Z', 'tipo_operacao': 'Operação contratual interna (com garantia da União)', 'finalidade': 'Infraestrutura', 'tipo_credor': 'Instituição Financeira Nacional', 'credor': 'Banco do Brasil S/A', 'moeda': 'Real', 'valor': 150000000, 'pvl_assoc_divida': 0, 'pvl_contradado_credor': 0, 'data_status': '16/10/2025'}, {'id_pleito': 65392, 'tipo_interessado': 'Município', 'interessado': 'Panambi', 'cod_ibge': 4313904, 'uf': 'RS', 'num_pvl': 'PVL02.001964/2023-50', 'status': 'Encaminhado à PGFN com manifestação técnica favorável', 'num_processo': '17944.102690/2023-88', 'data_protocolo': '2023-07-03T13:27:17Z', 'tipo_operacao': 'Operação contratual interna (com garantia da União)', 'finalidade': 'Infraestrutura', 'tipo_credor': 'Instituição Financeira Nacional', 'credor': 'Caixa Econômica Federal', 'moeda': 'Real', 'valor': 30000000, 'pvl_assoc_divida': 0, 'pvl_contradado_credor': 1, 'data_status': '24/07/2023'}, {'id_pleito': 67565, 'tipo_interessado': 'Município', 'interessado': 'Nísia Floresta', 'cod_ibge': 2408201, 'uf': 'RN', 'num_pvl': 'PVL02.004279/2023-85', 'status': 'Arquivado por decurso de prazo', 'num_processo': '17944.105989/2023-94', 'data_protocolo': '2023-12-26T14:36:46Z', 'tipo_operacao': 'Operação contratual interna', 'finalidade': 'Infraestrutura', 'tipo_credor': 'Instituição Financeira Nacional', 'credor': 'Caixa Econômica Federal', 'moeda': 'Real', 'valor': 21823450, 'pvl_assoc_divida': 0, 'pvl_contradado_credor': 0, 'data_status': '13/02/2025'}, {'id_pleito': 67570, 'tipo_interessado': 'Município', 'interessado': 'Jardim', 'cod_ibge': 5005004, 'uf': 'MS', 'num_pvl': 'PVL02.004269/2023-40', 'status': 'Arquivado por decurso de prazo', 'num_processo': '17944.106047/2023-23', 'data_protocolo': '2023-12-27T10:29:58Z', 'tipo_operacao': 'Operação contratual interna (com garantia da União)', 'finalidade': 'Infraestrutura', 'tipo_credor': 'Instituição Financeira Nacional', 'credor': 'Banco do Brasil S/A', 'moeda': 'Real', 'valor': 40000000, 'pvl_assoc_divida': 0, 'pvl_contradado_credor': 0, 'data_status': '14/10/2025'}, {'id_pleito': 68403, 'tipo_interessado': 'Município', 'interessado': 'Campo Largo', 'cod_ibge': 4104204, 'uf': 'PR', 'num_pvl': 'PVL02.000788/2024-10', 'status': 'Deferido (PVL-IF)', 'num_processo': None, 'data_protocolo': None, 'tipo_operacao': 'Operação contratual interna', 'finalidade': 'Infraestrutura', 'tipo_credor': 'Instituição Financeira Nacional', 'credor': 'Banco do Brasil S/A', 'moeda': 'Real', 'valor': 10000000, 'pvl_assoc_divida': 0, 'pvl_contradado_credor': 1, 'data_status': '30/04/2024'}, {'id_pleito': 69176, 'tipo_interessado': 'Município', 'interessado': 'Nova Esperança', 'cod_ibge': 4116901, 'uf': 'PR', 'num_pvl': 'PVL02.001399/2024-10', 'status': 'Deferido (PVL-IF)', 'num_processo': None, 'data_protocolo': None, 'tipo_operacao': 'Operação contratual interna', 'finalidade': 'Aquisição de máquinas, equipamentos e veículos', 'tipo_credor': 'Instituição Financeira Nacional', 'credor': 'Banco do Brasil S/A', 'moeda': 'Real', 'valor': 600000, 'pvl_assoc_divida': 0, 'pvl_contradado_credor': 1, 'data_status': '22/08/2024'}, {'id_pleito': 69284, 'tipo_interessado': 'Município', 'interessado': 'Icó', 'cod_ibge': 2305407, 'uf': 'CE', 'num_pvl': 'PVL02.001565/2024-70', 'status': 'Deferido (PVL-IF)', 'num_processo': None, 'data_protocolo': None, 'tipo_operacao': 'Operação contratual interna', 'finalidade': 'Infraestrutura', 'tipo_credor': 'Instituição Financeira Nacional', 'credor': 'Banco do Brasil S/A', 'moeda': 'Real', 'valor': 6000000, 'pvl_assoc_divida': 0, 'pvl_contradado_credor': 1, 'data_status': '26/08/2024'}, {'id_pleito': 65849, 'tipo_interessado': 'Município', 'interessado': 'Belo Campo', 'cod_ibge': 2903508, 'uf': 'BA', 'num_pvl': 'PVL02.002861/2023-15', 'status': 'Deferido (PVL-IF)', 'num_processo': None, 'data_protocolo': None, 'tipo_operacao': 'Operação contratual interna', 'finalidade': 'Infraestrutura', 'tipo_credor': 'Instituição Financeira Nacional', 'credor': 'Agência de Fomento do Estado da Bahia S/A', 'moeda': 'Real', 'valor': 6000000, 'pvl_assoc_divida': 0, 'pvl_contradado_credor': 1, 'data_status': '21/07/2023'}, {'id_pleito': 68808, 'tipo_interessado': 'Município', 'interessado': 'Salinas', 'cod_ibge': 3157005, 'uf': 'MG', 'num_pvl': 'PVL02.001113/2024-98', 'status': 'Deferido (PVL-IF)', 'num_processo': None, 'data_protocolo': None, 'tipo_operacao': 'Operação contratual interna', 'finalidade': 'Desenvolvimento sustentável', 'tipo_credor': 'Instituição Financeira Nacional', 'credor': 'Banco de Desenvolvimento de Minas Gerais S/A', 'moeda': 'Real', 'valor': 5000000, 'pvl_assoc_divida': 0, 'pvl_contradado_credor': 1, 'data_status': '14/06/2024'}, {'id_pleito': 68897, 'tipo_interessado': 'Município', 'interessado': 'Sapucaia do Sul', 'cod_ibge': 4320008, 'uf': 'RS', 'num_pvl': 'PVL02.000766/2024-50', 'status': 'Deferido', 'num_processo': '17944.003305/2024-00', 'data_protocolo': '2024-06-26T15:51:08Z', 'tipo_operacao': 'Operação contratual interna', 'finalidade': 'Infraestrutura', 'tipo_credor': 'Instituição Financeira Nacional', 'credor': 'BADESUL Desenvolvimento S.A. - Agência de Fomento/RS', 'moeda': 'Real', 'valor': 20000000, 'pvl_assoc_divida': 0, 'pvl_contradado_credor': 1, 'data_status': '02/07/2024'}, {'id_pleito': 68960, 'tipo_interessado': 'Município', 'interessado': 'Ortigueira', 'cod_ibge': 4117305, 'uf': 'PR', 'num_pvl': 'PVL02.001220/2024-16', 'status': 'Deferido (PVL-IF)', 'num_processo': None, 'data_protocolo': None, 'tipo_operacao': 'Operação contratual interna', 'finalidade': 'Infraestrutura', 'tipo_credor': 'Instituição Financeira Nacional', 'credor': 'Agência de Fomento do Paraná S/A', 'moeda': 'Real', 'valor': 6500000, 'pvl_assoc_divida': 0, 'pvl_contradado_credor': 1, 'data_status': '26/07/2024'}, {'id_pleito': 72588, 'tipo_interessado': 'Município', 'interessado': 'Goianira', 'cod_ibge': 5208806, 'uf': 'GO', 'num_pvl': 'PVL02.002059/2025-89', 'status': 'Em retificação pelo credor', 'num_processo': '17944.006547/2025-28', 'data_protocolo': '2026-04-24T09:04:19Z', 'tipo_operacao': 'Operação contratual interna (com garantia da União)', 'finalidade': 'Infraestrutura', 'tipo_credor': 'Instituição Financeira Nacional', 'credor': 'Caixa Econômica Federal', 'moeda': 'Real', 'valor': 49000000, 'pvl_assoc_divida': 0, 'pvl_contradado_credor': 0, 'data_status': '04/05/2026'}, {'id_pleito': 72610, 'tipo_interessado': 'Município', 'interessado': 'Águas Formosas', 'cod_ibge': 3100906, 'uf': 'MG', 'num_pvl': 'PVL02.002276/2025-79', 'status': 'Deferido (PVL-IF)', 'num_processo': None, 'data_protocolo': None, 'tipo_operacao': 'Operação contratual interna', 'finalidade': 'Infraestrutura', 'tipo_credor': 'Instituição Financeira Nacional', 'credor': 'Caixa Econômica Federal', 'moeda': 'Real', 'valor': 8500000, 'pvl_assoc_divida': 0, 'pvl_contradado_credor': 1, 'data_status': '29/01/2026'}, {'id_pleito': 72661, 'tipo_interessado': 'Município', 'interessado': 'Ipanema', 'cod_ibge': 3131208, 'uf': 'MG', 'num_pvl': 'PVL02.002346/2025-99', 'status': 'Deferido (PVL-IF)', 'num_processo': None, 'data_protocolo': None, 'tipo_operacao': 'Operação contratual interna', 'finalidade': 'Aquisição de máquinas, equipamentos e veículos', 'tipo_credor': 'Instituição Financeira Nacional', 'credor': 'Banco de Desenvolvimento de Minas Gerais S/A', 'moeda': 'Real', 'valor': 700000, 'pvl_assoc_divida': 0, 'pvl_contradado_credor': 1, 'data_status': '23/12/2025'}, {'id_pleito': 73156, 'tipo_interessado': 'Município', 'interessado': 'Uauá', 'cod_ibge': 2932002, 'uf': 'BA', 'num_pvl': 'PVL02.000410/2026-88', 'status': 'Deferido (PVL-IF)', 'num_processo': None, 'data_protocolo': None, 'tipo_operacao': 'Operação contratual interna', 'finalidade': 'Infraestrutura', 'tipo_credor': 'Instituição Financeira Nacional', 'credor': 'Caixa Econômica Federal', 'moeda': 'Real', 'valor': 28000000, 'pvl_assoc_divida': 0, 'pvl_contradado_credor': 1, 'data_status': '19/03/2026'}, {'id_pleito': 68671, 'tipo_interessado': 'Município', 'interessado': 'Arabutã', 'cod_ibge': 4201273, 'uf': 'SC', 'num_pvl': 'PVL02.000999/2024-52', 'status': 'Deferido (PVL-IF)', 'num_processo': None, 'data_protocolo': None, 'tipo_operacao': 'Operação contratual interna', 'finalidade': 'Aquisição de máquinas, equipamentos e veículos', 'tipo_credor': 'Instituição Financeira Nacional', 'credor': 'Agência de Fomento do Estado de Santa Catarina S/A', 'moeda': 'Real', 'valor': 4000000, 'pvl_assoc_divida': 0, 'pvl_contradado_credor': 1, 'data_status': '29/05/2024'}, {'id_pleito': 68672, 'tipo_interessado': 'Município', 'interessado': 'Arroio Grande', 'cod_ibge': 4301305, 'uf': 'RS', 'num_pvl': 'PVL02.001000/2024-92', 'status': 'Deferido (PVL-IF)', 'num_processo': None, 'data_protocolo': None, 'tipo_operacao': 'Operação contratual interna', 'finalidade': 'Caminho da Escola', 'tipo_credor': 'Instituição Financeira Nacional', 'credor': 'Banco do Estado do Rio Grande do Sul', 'moeda': 'Real', 'valor': 2445000, 'pvl_assoc_divida': 0, 'pvl_contradado_credor': 1, 'data_status': '10/06/2024'}, {'id_pleito': 68844, 'tipo_interessado': 'Município', 'interessado': 'Feira da Mata', 'cod_ibge': 2910776, 'uf': 'BA', 'num_pvl': 'PVL02.001131/2024-70', 'status': 'Deferido (PVL-IF)', 'num_processo': None, 'data_protocolo': None, 'tipo_operacao': 'Operação contratual interna', 'finalidade

In [18]:
df_geral = pd.DataFrame(data_json['items'])

In [20]:
df_pvl_rj = df_geral[df_geral['uf'] == 'RJ'].copy()
df_pvl_rj.head()

,id_pleito,tipo_interessado,interessado,cod_ibge,uf,num_pvl,status,num_processo,data_protocolo,tipo_operacao,finalidade,tipo_credor,credor,moeda,valor,pvl_assoc_divida,pvl_contradado_credor,data_status
43,71211,Município,Miguel Pereira,3302908,RJ,PVL02.000972/2025-41,Em retificação pelo interessado (PVL-IF),None,None,Operação contratual interna,Infraestrutura,Instituição Financeira Nacional,Caixa Econômica Federal,Real,49960000.0,0,0,14/07/2025
176,56075,Município,Resende,3304201,RJ,PVL02.003504/2022-85,Deferido (PVL-IF),None,None,Operação contratual interna,"Aquisição de máquinas, equipamentos e veículos",Instituição Financeira Nacional,Banco do Brasil S/A,Real,2160000.0,0,1,28/07/2022
214,68758,Município,Mesquita,3302858,RJ,PVL02.000008/2024-31,Arquivado por decurso de prazo,17944.002800/2024-93,2024-05-13T17:06:20Z,Operação contratual interna (com garantia da U...,Infraestrutura,Instituição Financeira Nacional,Caixa Econômica Federal,Real,40000000.0,0,0,14/10/2025
257,38893,Município,Paty do Alferes,3303856,RJ,PVL02.007600/2019-05,Deferido (PVL-IF),None,None,Operação contratual interna,"Aquisição de máquinas, equipamentos e veículos",Instituição Financeira Nacional,Agência de Fomento do Estado do Rio de Janeiro,Real,3512000.0,0,1,30/10/2019
337,42252,Município,Itatiaia,3302254,RJ,PVL02.000042/2020-82,Encaminhado à PGFN com manifestação técnica fa...,17944.101489/2020-31,2020-05-19T10:29:59Z,Operação contratual interna (com garantia da U...,Infraestrutura,Instituição Financeira Nacional,Banco do Brasil S/A,Real,30000000.0,1,1,21/05/2020

In [21]:
top_3_status = df_pvl_rj['status'].value_counts().head(3)

print("Os três status mais frequentes e suas frequências são:")
print(top_3_status)

Os três status mais frequentes e suas frequências são:
status
Deferido                                                 19
Encaminhado à PGFN com manifestação técnica favorável    13
Arquivado                                                11
Name: count, dtype: int64

In [22]:
df_pvl_rj['ano_status'] = df_pvl_rj['data_status'].astype(str).str.split('/').str[2]

df_pvl_rj[['data_status', 'ano_status']].head()

    data_status ano_status
43   14/07/2025       2025
176  28/07/2022       2022
214  14/10/2025       2025
257  30/10/2019       2019
337  21/05/2020       2020

In [23]:
frequencia_anos = df_pvl_rj['ano_status'].value_counts()

print("Frequência de solicitações por ano de status no RJ:")
print(frequencia_anos)

Frequência de solicitações por ano de status no RJ:
ano_status
2008    9
2007    8
2014    7
2012    6
2011    5
2009    5
2023    4
2025    3
2010    2
2020    1
2019    1
2022    1
2006    1
2003    1
2017    1
2004    1
2002    1
2026    1
2016    1
2015    1
2013    1
Name: count, dtype: int64

####  2) Melhorando a interação com o API
Observe dois URLs de consultas diferentes, por exemplo o URL utilizado em aula, e o URL feito no exercício anterior. Compare-os e observe as diferenças.

1. Faça uma função em Python que recebe como argumento o UF da consulta e o tipo de interessado (```'Estado'```ou ```Município```), e que devolve os dados da consulta no formato *DataFrame*.
2. Quantas solicitações para o Estado podem ser consultadas para Minas Gerais com *status* em 'Arquivado por decurso de prazo' estão registradas?
3. Qual é o município da Bahia com mais solicitações deferidas?
4. Salve um arquivo .csv com os dados de solicitações da Bahia, com interessado = 'Estado'

In [32]:
#1) 
import pandas as pd
import requests

print("Conectando à API do Tesouro Nacional... Aguarde...")

url_geral = "https://apidatalake.tesouro.gov.br/ords/sadipem/tt/pvl"
response = requests.get(url_geral)

if response.status_code == 200:
    dados_json = response.json()
    df_completo = pd.DataFrame(dados_json['items'])
    print(f"Sucesso! Carregamos {df_completo.shape[0]} registros gerais na memória.")
else:
    print(f"O servidor falhou com o código {response.status_code}. Execute esta célula novamente.")

Conectando à API do Tesouro Nacional... Aguarde...
Sucesso! Carregamos 5000 registros gerais na memória.

In [33]:
# 2) 
df_pvl_rj = df_completo[(df_completo['uf'] == 'RJ') & (df_completo['tipo_interessado'] == 'Municipio')].copy()
print("--- Item 1: Base do Rio de Janeiro criada com sucesso! ---\n")

print("--- Item 2: Três status mais frequentes no RJ ---")
top_3_status = df_pvl_rj['status'].value_counts().head(3)
print(top_3_status)
print("\n" + "="*50 + "\n")

df_pvl_rj['ano_status'] = df_pvl_rj['data_status'].astype(str).str.split('/').str[2]
print("--- Item 3: Coluna 'ano_status' gerada! Amostra dos dados: ---")
print(df_pvl_rj[['data_status', 'ano_status']].head(3))
print("\n" + "="*50 + "\n")

print("--- Item 4: Frequência de solicitações por ano no RJ ---")
frequencia_anos = df_pvl_rj['ano_status'].value_counts()
print(frequencia_anos)

--- Item 1: Base do Rio de Janeiro criada com sucesso! ---

--- Item 2: Três status mais frequentes no RJ ---
Series([], Name: count, dtype: int64)

==================================================

--- Item 3: Coluna 'ano_status' gerada! Amostra dos dados: ---
Empty DataFrame
Columns: [data_status, ano_status]
Index: []

==================================================

--- Item 4: Frequência de solicitações por ano no RJ ---
Series([], Name: count, dtype: int64)

In [34]:
# 3) 
def consultar_pvl(uf: str, tipo_interessado: str):
    tipo = tipo_interessado.lower().strip()
    if 'munic' in tipo:
        tipo_ajustado = 'Municipio'
    else:
        tipo_ajustado = 'Estado'
        
    df_filtrado = df_completo[
        (df_completo['uf'] == uf.upper()) & 
        (df_completo['tipo_interessado'] == tipo_ajustado)
    ].copy()
    
    return df_filtrado


print("--- Parte 2 / Item 1: Função 'consultar_pvl' registrada! ---\n")

df_mg_estado = consultar_pvl('MG', 'Estado')
qtd_arquivados_mg = df_mg_estado[df_mg_estado['status'] == 'Arquivado por decurso de prazo'].shape[0]
print(f"Item 2: Solicitações arquivadas por decurso de prazo em MG (Estado): {qtd_arquivados_mg}")
print("\n" + "-"*50 + "\n")

df_ba_municipios = consultar_pvl('BA', 'Municipio')
df_deferidos_ba = df_ba_municipios[df_ba_municipios['status'].str.contains('Deferido', na=False)]
top_municipio_ba = df_deferidos_ba['interessado'].value_counts().head(1)
print("Item 3: Município da BA com mais solicitações deferidas e a quantidade:")
print(top_municipio_ba)
print("\n" + "-"*50 + "\n")

df_ba_estado = consultar_pvl('BA', 'Estado')
df_ba_estado.to_csv('solicitacoes_estado_bahia.csv', sep=';', index=False, encoding='utf-8-sig')
print("Item 4: Arquivo 'solicitacoes_estado_bahia.csv' exportado com sucesso no seu diretório!")

--- Parte 2 / Item 1: Função 'consultar_pvl' registrada! ---

Item 2: Solicitações arquivadas por decurso de prazo em MG (Estado): 0

--------------------------------------------------

Item 3: Município da BA com mais solicitações deferidas e a quantidade:
Series([], Name: count, dtype: int64)

--------------------------------------------------

Item 4: Arquivo 'solicitacoes_estado_bahia.csv' exportado com sucesso no seu diretório!

In [35]:
# 4) 
def consultar_pvl(uf: str, tipo_interessado: str):
    tipo = tipo_interessado.lower().strip()
    if 'munic' in tipo:
        tipo_ajustado = 'Municipio'
    else:
        tipo_ajustado = 'Estado'
        
    df_filtrado = df_completo[
        (df_completo['uf'] == uf.upper()) & 
        (df_completo['tipo_interessado'] == tipo_ajustado)
    ].copy()
    
    return df_filtrado


print("--- Parte 2 / Item 1: Função 'consultar_pvl' registrada! ---\n")

df_mg_estado = consultar_pvl('MG', 'Estado')
qtd_arquivados_mg = df_mg_estado[df_mg_estado['status'] == 'Arquivado por decurso de prazo'].shape[0]
print(f"Item 2: Solicitações arquivadas por decurso de prazo em MG (Estado): {qtd_arquivados_mg}")
print("\n" + "-"*50 + "\n")

df_ba_municipios = consultar_pvl('BA', 'Municipio')
df_deferidos_ba = df_ba_municipios[df_ba_municipios['status'].str.contains('Deferido', na=False)]
top_municipio_ba = df_deferidos_ba['interessado'].value_counts().head(1)
print("Item 3: Município da BA com mais solicitações deferidas e a quantidade:")
print(top_municipio_ba)
print("\n" + "-"*50 + "\n")

df_ba_estado = consultar_pvl('BA', 'Estado')
df_ba_estado.to_csv('solicitacoes_estado_bahia.csv', sep=';', index=False, encoding='utf-8-sig')
print("Item 4: Arquivo 'solicitacoes_estado_bahia.csv' exportado com sucesso no seu diretório!")

--- Parte 2 / Item 1: Função 'consultar_pvl' registrada! ---

Item 2: Solicitações arquivadas por decurso de prazo em MG (Estado): 0

--------------------------------------------------

Item 3: Município da BA com mais solicitações deferidas e a quantidade:
Series([], Name: count, dtype: int64)

--------------------------------------------------

Item 4: Arquivo 'solicitacoes_estado_bahia.csv' exportado com sucesso no seu diretório!